/** Static Products route and invention catalogue interface copy. */
export const productsContent = {
  metadata: {
    title: 'Inventions, Prototypes & Engineered Products',
    description:
      'Explore inventions, research experiments, prototypes, and engineered products developed by Phenix Labs, ordered by their project dates.',
    keywords: [
      'Phenix Labs inventions',
      'engineering prototypes',
      'product development',
      'technology experiments',
    ],
    path: '/products',
    breadcrumbLabel: 'Products',
    schemaTitle: 'Inventions and Products',
    schemaDescription:
      'A growing catalogue of inventions, prototypes, experiments, and engineered products.',
  },
  hero: {
    sectionLabel: 'Products overview',
    eyebrow: 'Ideas made tangible',
    title: 'Inventions shaped through',
    highlightedTitle: 'curiosity and engineering.',
    description:
      'A growing archive of prototypes, experiments, and engineered products—each one built to explore an idea, test a principle, or solve a real-world problem.',
    capabilities: [
      { key: 'systems', label: 'Engineered systems' },
      { key: 'prototypes', label: 'Physical prototypes' },
      { key: 'research', label: 'Research experiments' },
    ],
    orbitSteps: [
      { number: '01', text: 'Observe' },
      { number: '02', text: 'Prototype' },
      { number: '03', text: 'Validate' },
    ],
  },
  catalogue: {
    sectionLabel: 'Invention catalogue',
    eyebrow: 'The collection',
    title: 'Explore what we have brought to life.',
    description:
      'Search the archive or change its order. New published work appears automatically from the admin panel.',
    searchPlaceholder: 'Search inventions',
    searchAction: 'Search',
    searchLabel: 'Search inventions',
    clearSearchLabel: 'Clear invention search',
    sortLabel: 'Sort inventions',
    sortOptions: {
      latest: 'Newest invention date',
      oldest: 'Oldest invention date',
      'title-asc': 'Title A–Z',
      'title-desc': 'Title Z–A',
    },
    updating: 'Updating collection…',
    resultNoun: 'invention',
    resultNounPlural: 'inventions',
    matchingLabel: 'matching',
    showingLabel: 'Showing',
    ofLabel: 'of',
    noSearchTitle: 'No inventions match that search',
    emptyTitle: 'The invention archive is taking shape',
    noSearchDescription: 'Try a broader phrase or clear the current search.',
    clearSearchAction: 'Clear search',
    emptyDescription:
      'Published inventions will appear here as they are added in the admin panel.',
    loadMore: 'Load more inventions',
    loadingMore: 'Loading inventions',
    end: 'You’ve reached the end of the invention collection.',
    loadError: 'More inventions could not be loaded. Please try again.',
    updateError: 'The invention collection could not be updated. Please try again.',
    cardFallback: 'More information about this invention will be added soon.',
    detailFallback: 'Additional product details will be added soon.',
    cardEyebrow: 'Invention',
    openDetailsPrefix: 'Open details for',
    previousImagePrefix: 'Show previous image of',
    nextImagePrefix: 'Show next image of',
    showImagePrefix: 'Show image',
    imageOfLabel: 'of',
    visualRecordLabel: 'Visual record',
    zoomNavigatorLabel: 'Zoom navigator',
    dateLabels: {
      started: 'Started',
      completed: 'Completed',
      added: 'Added',
    },
    featuredLabel: 'Featured invention',
    workspaceEyebrow: 'Product workspace',
    workspaceTitle: 'Invention detail',
    detailsEyebrow: 'Invention details',
    aboutTitle: 'About this invention',
    previousLabel: 'Show previous invention',
    nextLabel: 'Show next invention',
    closeLabel: 'Close invention details',
  },
} as const
